<%@ Page Title="" Language="C#" MasterPageFile="~/Client.Master" AutoEventWireup="true" CodeBehind="role.aspx.cs" Inherits="DensNDente_Warehouse_Management.WebForm3" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">


    <div>

        <div style="width: 100%; float: left;">

            <table>
                <tr>
                    <td></td>
                    <td style="font-weight: bold; font-size: 26px; color: #ed4e6e">Add New Role</td>
                </tr>
                <tr>
                    <td>Role Name:</td>
                    <td>
                        <asp:TextBox ID="txtRoleName" runat="server" title="Role name is required" required></asp:TextBox>

                    </td>

                </tr>

                <tr>
                    <td></td>
                    <td>
                        <asp:CheckBox ID="ckStock" runat="server" Text="Stock Module" />

                    </td>

                </tr>
                <tr>
                    <td></td>
                    <td>
                        <asp:CheckBox ID="ckSale" runat="server" Text="Sales Module" /></td>

                </tr>
                <tr>
                    <td></td>
                    <td>
                        <asp:CheckBox ID="ckPurchase" runat="server" Text="Purchase Module" /></td>

                </tr>
                <tr>
                    <td></td>
                    <td>
                        <asp:CheckBox ID="ckAdmin" runat="server" Text="Employee Module" /></td>

                </tr>
                <tr>
                    <td></td>
                    <td>
                        <asp:CheckBox ID="ckPayroll" runat="server" Text="Payroll Module" /></td>

                </tr>
                <tr>
                    <td></td>
                    <td>
                        <asp:CheckBox ID="ckSalestarget" runat="server" Text="SalesTarget Module" /></td>

                </tr>
                <tr>
                    <td></td>
                    <td>
                        <asp:CheckBox ID="ckReports" runat="server" Text="Reports Module" /></td>

                </tr>

                <tr>
                    <td></td>
                    <td>
                        <asp:Button ID="btnInsert" runat="server" Text="Add New Role" CssClass="button" OnClick="btnInsert_Click" />
                        <asp:Button ID="btnUpdate" runat="server" Text="Update Employee" CssClass="button" Visible="false" OnClick="btnUpdate_Click" />
                        <asp:HyperLink ID="linkBack" CssClass="button-cancel" runat="server" NavigateUrl="~/Pages/role.aspx" Visible="false">Cancel</asp:HyperLink>
                    </td>

                </tr>

            </table>
        </div>

        <div style="width: 100%; float: left">

            <div class="gridHeaderStyle">
                View All Roles
            </div>
            <div>

                <asp:GridView ID="gridRole" runat="server" AutoGenerateColumns="false" DataKeyNames="RoleId" Width="100%" CssClass="ctable" AutoGenerateDeleteButton="True" OnRowDeleting="gridRole_RowDeleting">
                    <Columns>
                        <asp:TemplateField>
                            <ItemTemplate>
                                <a href="role.aspx?id=<%# Eval("RoleId") %>">Edit</a>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:BoundField  DataField="RoleName" HeaderText="Name"/>
                        <asp:BoundField DataField="Stock" HeaderText="Stock" />
                        <asp:BoundField DataField="Sales" HeaderText="Sales" />
                        <asp:BoundField DataField="Purchase" HeaderText="Purchase" />
                        <asp:BoundField DataField="Admin" HeaderText="Employee" />
                        <asp:BoundField DataField="Payroll" HeaderText="Payroll" />
                        <asp:BoundField DataField="SalesTarget" HeaderText="Sales Target" />
                        <asp:BoundField DataField="Reports" HeaderText="Reports" />

                    </Columns>

                </asp:GridView>
            </div>
        </div>


    </div>

</asp:Content>
