<%@ Page Title="" Language="C#" MasterPageFile="~/Client.Master" AutoEventWireup="true" CodeBehind="salary.aspx.cs" Inherits="DensNDente_Warehouse_Management.WebForm12" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">

    <div style="width: 100%; float: left">
        <div style="width: 50%; float: left">
            <table>
                  <tr>
                    <td class="auto-style1"></td>
                    <td style="font-weight: bold; font-size: 26px; color: #ed4e6e">Add New Salary</td>
                </tr>
                <tr>
                    <td>Employee Name</td>

                    <td>
                        <asp:DropDownList ID="cbEmployee" runat="server" required></asp:DropDownList>
                    </td>
                </tr>
                <tr>
                    <td>Start Date</td>
                    <td>
                        <asp:TextBox ID="txtStartDate" runat="server" type="date" required></asp:TextBox>
                    </td>
                </tr>
                <tr>
                    <td>End Date</td>
                    <td>
                        <asp:TextBox ID="txtEndDate" runat="server" type="date" required></asp:TextBox></td>
                </tr>


            </table>
        </div>
        <div style="width: 50%; float: left">
            <table>
                 <tr style="height: 34px;">
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>Total Hours</td>
                    <td>
                        <asp:TextBox ID="txtTotalHours" runat="server" Text="176" required></asp:TextBox>
                    </td>
                </tr>
                <tr>
                    <td>Total Salary</td>
                    <td>
                        <asp:Label ID="lblTotalSalary" runat="server"></asp:Label>
                    </td>

                </tr>
                <tr>
                    <td></td>
                    <td>
                        <asp:Button ID="btnInsert" runat="server" Text="Add New Salary" CssClass="button" OnClick="btnInsert_Click" />
                        <asp:Button ID="btnUpdate" runat="server" Text="Update Salary" CssClass="button" Visible="false" OnClick="btnUpdate_Click" />
                        <asp:HyperLink ID="linkBack" CssClass="button-cancel" runat="server" NavigateUrl="~/Pages/salary.aspx" Visible="false">Cancel</asp:HyperLink>
                    </td>
                </tr>
            </table>
        </div>
    </div>
    <div style="width: 100%; float: left">
        <div class="gridHeaderStyle">
            View All Salary
        </div>
        <div>
            <asp:GridView Width="100%" ID="gridSalary" runat="server" DataKeyNames="SalaryId" OnRowDeleting="gridSalary_RowDeleting" AutoGenerateColumns="false" CssClass="ctable" AutoGenerateDeleteButton="True">
                <Columns>
                    <asp:TemplateField>
                        <ItemTemplate>
                            <a href="salary.aspx?id=<%# Eval("SalaryId") %>">Edit</a>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:BoundField DataField="FirstName" HeaderText="Employee Name" />
                    <asp:BoundField DataField="StartDate" HeaderText="Start Date" />
                    <asp:BoundField DataField="EndDate" HeaderText="End Date" />
                    <asp:BoundField DataField="TotalHours" HeaderText="Total Hours" />
                    <asp:BoundField DataField="TotalSalary" HeaderText="Total Salary" DataFormatString="{0:c}" />
                </Columns>
            </asp:GridView>
        </div>
    </div>
</asp:Content>
