//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DensNDente_Warehouse_Management.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DensDBEntities : DbContext
    {
        public DensDBEntities()
            : base("name=DensDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tblBin> tblBins { get; set; }
        public DbSet<tblCustomer> tblCustomers { get; set; }
        public DbSet<tblPermission> tblPermissions { get; set; }
        public DbSet<tblRole> tblRoles { get; set; }
        public DbSet<tblSalesTarget> tblSalesTargets { get; set; }
        public DbSet<tblEmployee> tblEmployees { get; set; }
        public DbSet<tblNewsLetter> tblNewsLetters { get; set; }
        public DbSet<tblProduct> tblProducts { get; set; }
        public DbSet<tblPurchaseOrder> tblPurchaseOrders { get; set; }
        public DbSet<tblPurchaseOrderDetail> tblPurchaseOrderDetails { get; set; }
        public DbSet<tblSalary> tblSalaries { get; set; }
        public DbSet<tblSaleInvoice> tblSaleInvoices { get; set; }
        public DbSet<tblSaleInvoiceDetail> tblSaleInvoiceDetails { get; set; }
        public DbSet<tblVendor> tblVendors { get; set; }
    }
}
