//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DensNDente_Warehouse_Management.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNewsLetter
    {
        public int NewsId { get; set; }
        public System.DateTime NewsDate { get; set; }
        public string Message { get; set; }
        public bool Deleted { get; set; }
    }
}
