//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DensNDente_Warehouse_Management.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPurchaseOrderDetail
    {
        public int PODetailId { get; set; }
        public int POId { get; set; }
        public int ProductId { get; set; }
        public Nullable<decimal> Price { get; set; }
        public bool Deleted { get; set; }
        public int ReceivedQuantity { get; set; }
        public bool Recieved { get; set; }
    
        public virtual tblProduct tblProduct { get; set; }
        public virtual tblPurchaseOrder tblPurchaseOrder { get; set; }
    }
}
