//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DensNDente_Warehouse_Management.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPermission
    {
        public int PermissionId { get; set; }
        public int RoleId { get; set; }
        public bool Insert_Item { get; set; }
        public bool Update_Item { get; set; }
        public bool Delete_Item { get; set; }
        public bool View_Item { get; set; }
        public bool Deleted { get; set; }
    
        public virtual tblRole tblRole { get; set; }
    }
}
