//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DensNDente_Warehouse_Management.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProduct
    {
        public tblProduct()
        {
            this.tblPurchaseOrderDetails = new HashSet<tblPurchaseOrderDetail>();
            this.tblSaleInvoiceDetails = new HashSet<tblSaleInvoiceDetail>();
        }
    
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public string ProductDescription { get; set; }
        public bool Deleted { get; set; }
        public int BinId { get; set; }
        public decimal StandardCost { get; set; }
        public int SafetyStockLevel { get; set; }
        public int ReorderPoint { get; set; }
        public string ImagePath { get; set; }
        public int Quantity { get; set; }
        public decimal SellingCost { get; set; }
    
        public virtual ICollection<tblPurchaseOrderDetail> tblPurchaseOrderDetails { get; set; }
        public virtual ICollection<tblSaleInvoiceDetail> tblSaleInvoiceDetails { get; set; }
        public virtual tblBin tblBin { get; set; }
    }
}
