//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DensNDente_Warehouse_Management.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSaleInvoice
    {
        public tblSaleInvoice()
        {
            this.tblSaleInvoiceDetails = new HashSet<tblSaleInvoiceDetail>();
        }
    
        public int InvoiceId { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public int CustomerId { get; set; }
        public decimal TotalSale { get; set; }
        public decimal Tax { get; set; }
        public decimal Discount { get; set; }
        public decimal NetSale { get; set; }
        public bool Deleted { get; set; }
    
        public virtual tblCustomer tblCustomer { get; set; }
        public virtual ICollection<tblSaleInvoiceDetail> tblSaleInvoiceDetails { get; set; }
    }
}
