//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DensNDente_Warehouse_Management.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSalary
    {
        public int SalaryId { get; set; }
        public decimal TotalSalary { get; set; }
        public bool Deleted { get; set; }
        public int EmployeeId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public double TotalHours { get; set; }
    
        public virtual tblEmployee tblEmployee { get; set; }
    }
}
