//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DensNDente_Warehouse_Management.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSalesTarget
    {
        public int SalesTargetId { get; set; }
        public int MonthName { get; set; }
        public int YearName { get; set; }
        public int TargetAmount { get; set; }
        public int AchievedAmount { get; set; }
        public bool Deleted { get; set; }
    }
}
